paths:

  # Todos los productos
  /api/products:
    # GET
    get:
      summary: Listar todos los productos
      description: Obtiene una lista de todos los productos disponibles.
      tags:
        - Products
      responses:
        '200':
          description: Lista de productos obtenida exitosamente
          # content:
          #   application/json:
          #     schema:
          #       type: array
          #       items:
          #         $ref: '#/components/schemas/Product'
        '500':
          description: Error al obtener los productos
    # POST
    post:
      summary: Añadir un nuevo producto
      description: Agrega un nuevo producto.
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createProduct'
      responses:
        '200':
          description: Producto agregado exitosamente
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/Product'
        '400':
          description: Datos inválidos o el código del producto ya existe
        '500':
          description: Error al agregar el producto

  # ID de un producto
  /api/products/{pid}:
    # GET
    get:
      summary: Obtener un producto por ID
      description: Obtiene la información de un producto específico usando su ID.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto encontrado
          # content:
          #   application/json:
          #     schema:
          #       type: array
          #       items:
          #         $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error al obtener el producto
    # PUT
    put:
      summary: Actualizar un producto por ID
      description: Actualiza la información de un producto específico usando su ID.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
      responses:
        '200':
          description: Producto actualizado exitosamente
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/Product'
        '400':
          description: Datos inválidos o el código del producto ya existe
        '404':
          description: Producto no encontrado
        '500':
          description: Error al actualizar el producto
    # DELETE
    delete:
      summary: Eliminar un producto por ID
      description: Elimina la información de un producto específico usando su ID.
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error al obtener el producto

# ==================================================================================================================

components:

  # SCHEMAS
  schemas:
    Product:
      type: object 
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto 
        price:
          type: number
          description: Precio del producto
        img:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: El código único del producto
          uniqueItems: true
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          description: Categoría del producto
        status:
          type: boolean
          description: Estado del producto (disponible o no)
        thumbnails:
          type: array
          items:
            type: string
          description: Lista de URLs de las miniaturas del producto
        owner:
          type: string
          description: Propietario del producto
          default: 'admin'
      required:
        - title
        - description
        - price
        - code
        - stock
        - category
        - status
      example:
        title: "Título de un producto"
        description: "Descripción de un producto"
        price: 100.0
        img: "img/example.jpg"
        code: "example123"
        stock: 50
        category: "Categoría del producto"
        status: true
        thumbnails:
          - "img/thumb1.jpg"
          - "img/thumb2.jpg"
        owner: "example"

  # REQUEST BODIES
  requestBodies:
    # CREATE
    createProduct:
      type: object 
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto 
        price:
          type: number
          description: Precio del producto
        img:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: El código único del producto
          uniqueItems: true
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          description: Categoría del producto
        status:
          type: boolean
          description: Estado del producto (disponible o no)
        thumbnails:
          type: array
          items:
            type: string
          description: Lista de URLs de las miniaturas del producto
        owner:
          type: string
          description: Propietario del producto
          default: 'admin'
      required:
        - title
        - description
        - price
        - code
        - stock
        - category
        - status
      example:
        title: "Swaggeresas"
        description: "Test de Swagger."
        price: 1000.0
        img: "img/swagger.jpg"
        code: "swagger777"
        stock: 10
        category: "Swagger"
        status: true
        thumbnails: []
        owner: "swagger"
    # UPDATE
    updateProduct:
          type: object
          properties:
            _id:
              type: ObjectId
              description: ID autogenerado por MongoDB
            title:
              type: string
              description: Título del producto
            description:
              type: string
              description: Descripción del producto
            price:
              type: number
              description: Precio del producto
            img:
              type: string
              description: URL de la imagen del producto
            code:
              type: string
              description: El código único del producto
              uniqueItems: true
            stock:
              type: number
              description: Cantidad en stock del producto
            category:
              type: string
              description: Categoría del producto
            status:
              type: boolean
              description: Estado del producto (disponible o no)
            thumbnails:
              type: array
              items:
                type: string
              description: Lista de URLs de las miniaturas del producto
            owner:
              type: string
              description: Propietario del producto
              default: 'admin'
          example:
            title: "Swaggeresas Mejoradas"
            description: "Pasaron las pruebas de Swagger."
            price: 1500.0
            code: "swagger778"
            stock: 30
            category: "Categoría actualizada"